Add MTooltip
TizenAPI/Tizen.NET.MaterialComponents pull request #35
Opened 2019-04-26 07:01 UTC by flyofsky

### Description of Change ###
This PR is for adding Tooltip of Material Design on Tizen

### Issues Resolved ### 
- fixes #27 

### API Changes ###
 None

### Platforms Affected ### 
- Tizen

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
![tooltip](https://user-images.githubusercontent.com/16184582/56789275-7f9f8d00-683c-11e9-8494-3d13747caea3.gif)

### PR Checklist ###

- [ ] Has automated tests 
- [x] Rebased on top of the target branch at time of PR
- [x] Changes adhere to coding standard

2019-05-02 01:21 UTC, rookiejava reviewed
What do you think about providing attached properties instead?

2019-05-15 03:15 UTC, rookiejava commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static void UnSetMTooltip(this EvasObject parent)
UnSetMToooltip -> UnsetMTooltip
To be honest, I don't like this naming. I think there is better naming.

2019-05-15 03:15 UTC, rookiejava commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static void SetMTooltip(this EvasObject parent, string text)
parent -> object or control or something else would be better.

2019-05-15 08:39 UTC, flyofsky commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static void UnSetMTooltip(this EvasObject parent)
Remove this Method

2019-05-15 08:39 UTC, flyofsky commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static void SetMTooltip(this EvasObject parent, string text)
Done

2019-05-16 01:45 UTC, rookiejava requested changes

2019-05-16 01:45 UTC, rookiejava commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +            control.TooltipStyle = "material";
"material" => Styles.Material

2019-05-16 01:45 UTC, rookiejava commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +            if(control.TooltipStyle == "material" && control.TooltipOrientation == TooltipOrientation.Bottom)
return control.TooltipStyle == Styles.Material && control.TooltipOrientation == TooltipOrientation.Bottom;

2019-05-16 01:45 UTC, rookiejava commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static bool IsUsedMTooltip(this EvasObject control)
IsUsingMTooltip

2019-05-16 02:28 UTC, flyofsky commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +            control.TooltipStyle = "material";
Done

2019-05-16 02:28 UTC, flyofsky commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +            if(control.TooltipStyle == "material" && control.TooltipOrientation == TooltipOrientation.Bottom)
Done

2019-05-16 02:28 UTC, flyofsky commented on src/Tizen.NET.MaterialComponents/Components/MTooltip.cs
> +        public static bool IsUsedMTooltip(this EvasObject control)
Done

2019-05-16 06:58 UTC, rookiejava approved these changes

2019-05-16 06:59 UTC, merged